#!/bin/bash

function is_osx() {
    local platform=$(uname)
    [ "$platform" == "Darwin" ]
}

# ============================================================================ #
# VARIABLES
# ============================================================================ #

BIN="$HOME/.dotfiles_bin"

# Dotfiles
TMUX_CONF="$HOME/.tmux.conf"
MY_TMUX_CONF_ORIGINAL="./tmux.conf"
MY_TMUX_CONF="${BIN}/tmux.conf"

# Git directories
TMUX_SENSIBLE="${BIN}/tmux-sensible"
TMUX_YANK="${BIN}/tmux-yank"


# ============================================================================ #
# MAIN
# ============================================================================ #

# Delete directories and files
rm -f ${TMUX_CONF}

# Create directories and files
mkdir ${BIN}
cp ${MY_TMUX_CONF_ORIGINAL} ${MY_TMUX_CONF}

# Setup TMUX configuration files
if [ -d "${TMUX_SENSIBLE}" ]; then
    echo "tmux-sensible already installed ..."
else
    git clone https://github.com/tmux-plugins/tmux-sensible.git ${TMUX_SENSIBLE}
fi
if [ -d "${TMUX_YANK}" ]; then
    echo "tmux-yank already installed ..."
else
    git clone https://github.com/tmux-plugins/tmux-yank ${TMUX_YANK}
fi
ln -s ${MY_TMUX_CONF} ${TMUX_CONF}

# Miscellaneous modules
if is_osx; then
    brew install ripgrep
fi
if is_osx; then
    brew install fzf
    $(brew --prefix fzf)/install --all
fi
